### ISSUE TITLE
Crash caused by light fix stare

### ISSUE THREAD

**Issue by facetorched** [makamys/CoreTweaks#7]
A player on a server ran into this crash. Disabling lightfixstare in the config resolved the issue.
The only info I know is they were looking in the general direction of some carpenter's buttons.

```
java.lang.NullPointerException: Exception in world tick
	at makamys.coretweaks.tweak.LightFixStare.postPlayerCheckLight(LightFixStare.java:16)
	at net.minecraft.world.World.handler$postPlayerCheckLight$zef000(World.java:52602)
	at net.minecraft.world.World.func_72903_x(World.java:2824)
	at net.minecraft.world.World.func_147456_g(World.java:2861)
	at net.minecraft.client.multiplayer.WorldClient.func_147456_g(WorldClient.java:134)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:113)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2024)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4002)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by makamys** [comment]
Are you using the latest version? I believe I have fixed this already.

**Comment by facetorched** [comment]
Yes. Sorry. Was using 0.2.5
